language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
  - master

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --testdox
#script: phpunit --coverage-text