language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
  - master

before_install: composer self-update

install: composer install

script: phpunit --testdox
#script: phpunit --coverage-text
